### ISSUE TITLE
maas.io not rendering indentation in LXD profile config snippet

### ISSUE THREAD

**Issue by szeestraten** [CanonicalLtd/maas-docs#142]
The docs on maas.io seem to not render the right YAML indentation for the LXD profile config snippet.
See: http://maas.io/docs/en/installconfig-lxd-install vs [installconfig-lxd-install.md](https://github.com/CanonicalLtd/maas-docs/blob/441e82573327aa16cc80dfc443118ceadde2a70d/en/installconfig-lxd-install.md#create-a-lxc-profile-for-maas)

Copying straight from the example snippet leads to LXC not parsing the config file.

**Comment by pmatulis** [comment]
@nottrobin Did something change with the site design (I did notice that the look has changed in other ways)? I do not recall if YAML syntax highlighting preserved whitespace. The [source](https://git.io/vPyuY) looks fine:

```
config:
  raw.lxc: |-
    lxc.cgroup.devices.allow = c 10:237 rwm
    lxc.aa_profile = unconfined
    lxc.cgroup.devices.allow = b 7:* rwm
  security.privileged: "true"
```

**Comment by nottrobin** [comment]
This is to do with the styling of `<code>` elements in maas.io, and it has existed for a while. I think it's actually been a problem ever since the maas.io/docs first went live.

The new version of the docs doesn't have this problem. But for now I've just implemented a hack to fix it in http://maas.io: https://github.com/ubuntudesign/maas.io/issues/75. I can get it live as soon as it's been reviewed.
