### ISSUE TITLE
how to create a custom ephemeral-v3 maas image

### ISSUE THREAD

**Issue by aperez900907** [CanonicalLtd/maas-docs#593]
Hello i need find docs about how i can create a personalized maas image ephemeral-v3 and understand the process.
the maas-image-builder was removed in this version of the docs, so i assume don't work on the latets release.

Please, any documetation will be very helpfull.

**Comment by ArKam** [comment]
I would be thrilled to have one too.

**Comment by degville** [comment]
Thanks for letting us know. Custom image creation and deployment is available with enterprise support (see 'Enterprise support for MAAS' on https://maas.io/), but we'll bring up this request with the MAAS team.

**Comment by ArKam** [comment]
Hi @degville, In my humble opinion, having a way to push custom images on maas freely without having to subscribe for a enterprise license would be economically viable as it would allow more and more company to bring support to Maas.

I now that everyone deserve to be paid but it would be better to enforce a licensing as soon as a regionD is managing a certain amount of nodes rather having to purchase an enterprise plan. Plus this plan is difficult to get in as it require to contact ubuntu sales and sign a contract. Not really what we could call a cloud flexible way to do things ;-)

But I’ll respect the team decision as it’s your own product with a lot of development effort coming from ubuntu rather than the community.

**Comment by degville** [comment]
Thanks for this valuable feedback. We've discussed this with the MAAS team and it's definitely something we'll keep in mind.

**Comment by p4t0k** [comment]
I know this is an old issue and closed, but I agree with what ArKam wrote here. Images available in the free MAAS version are tragically limiting. Making more images and custom images available to the free community MAAS version would make it much more interesting for companies and that would be beneficial for Canonical as well because you have other products that are somehow connected to MAAS (eg. openstack, microk8s). Otherwise, people will consider other solutions like Ironic and MAAS will die by slow painful death. I would rather see MAAS being a serious competitor for Ironic.

**Comment by desrod** [comment]
@p4t0k You might want to look into [packer-maas](https://github.com/canonical/packer-maas/) and consider contributing there. Many community members have helped improve the quality of the templates through filing issues and PRs.
