### ISSUE TITLE
Broken link on Install MAAS Cli to hardware config info

### ISSUE THREAD

**Issue by GitVail** [CanonicalLtd/maas-docs#88]
On the Install MAAS by Packages page there is a link (http://maas.io/docs/orientation#a-typical-maas-setup) to see hardware configuration info and it goes to 404: page not found.

**Comment by pmatulis** [comment]
Thank you. This will be fixed today.

**Comment by GitVail** [comment]
Thank you Peter.
The missing info wouldn't have been too bad, but I also couldn't find that information any other way. Not in the table of contents. No search is available.

I trying to learn about clouds. How to set one up for engineering purposes so we can test our newest hardware's performance on cloud systems and supporting cloud services. Ubuntu and MAAS seemed like the easiest way to get started. But I have run into some trouble.

Thought I would start with the newer Ubuntu 16.04. That was going along fine until I got to the configuring MAAS part of the instructions. U16.04 gets MAAS 2.0 and there is no "Clusters" tab on the 2.0 page.

So I started over with 14.04 server (as specified) and that was going fine until I go to #5 in your instructions which says "Go to the "Clusters" tab,…". In the text mode world of Ubuntu server there are no tabs. No gui. So I installed Ubuntu-desktop, which came up with only one of my NIC's. So I fixed that by changing "managed=false" to true. The eth0 then came up. But now MAAS only showed one connection (eth0 the external). So I rebooted and no keyboard or mouse. It's like the usb ports are dead. And when booting I see many dozens or hundreds of messages "Starting MAAS region controller (worker)". Until the desktop starts, with no keyboard or mouse. Tried many ports. Other keyboards. Nothing.

I'm going to start again with Ubuntu 14.04 Desktop…

-Dick

**Comment by pmatulis** [comment]
> Thought I would start with the newer Ubuntu 16.04. That was going along fine until I got to the configuring MAAS part of the instructions. U16.04 gets MAAS 2.0 and there is no "Clusters" tab on the 2.0 page.

I would recommend 16.04 Ubuntu Server at this time.

Where did you see reference to a Clusters tab in the 2.0 documentation?

**Comment by GitVail** [comment]
It's on the Get Started page which doesn't specify which version of Ubuntu Server to use. I didn't find any documentation that didn't say Cluster tab. If there is a doc please send a link.
Thanks
Dick Vail

-Dick

**Comment by GitVail** [comment]
It's also on the Get OpenStack Autopilot page, but that page says to use Ubuntu Server 14.04 LTS.

BTW, what needs more explanation on the Get Started pages is the networking. IP's for private and external, Gateways, Subnet Masks, etc. One reason I wanted to see the typical hardware setup info was to understand the various ways hardware could be setup. Whether an actual router was needed or could the Controller do all of the DHCP, DNS, and routing.

-Dick

**Comment by GitVail** [comment]
I found really detailed instructions here http://blog.naydenov.net/2015/11/deploying-openstack-on-maas-1-9-with-juju-network-setup/


-Dick

**Comment by pmatulis** [comment]
Right. Don't use http://maas.io/get-started . Use the regular documentation: http://maas.io/docs

**Comment by GitVail** [comment]
The link below still doesn't work
Install from MAAS Packages
Installing MAAS from packages is straightforward. There are actually several packages that go into making up a working MAAS install, but for convenience, many of these have been gathered into a virtual package called 'maas' which will install the necessary components for a 'seed cloud', that is a single server that will directly control a group of nodes. The main packages are:

  *   maas - seed cloud setup, which includes both the region controller and the rack controller below.
  *   maas-region-controller - includes the web UI, API and database.
  *   maas-rack-controller - controls a group of machines under a rack or multiple racks, including DHCP management.
  *   maas-dhcp/maas-dns - required when managing dhcp/dns.
  *   maas-proxy - required to provide a MAAS proxy.
If you need to separate these services or want to deploy an additional rack controller, you should install the corresponding packages individually (see the description of a typical setup<http://maas.io/docs/orientation#a-typical-maas-setup> for more background on how a typical hardware setup might be arranged).


-Dick

**Comment by pmatulis** [comment]
@GitVail Thanks for sticking with this. :cake:  The underlying documentation is fixed, with quite a few other improvements, but we are going through some changes with respect to how this stuff gets published on our web site. Please be patient. It will all be updated in the next few hours.

**Comment by GitVail** [comment]
Hi Peter,
The maas.io/docs page gives the instructions for 2.0 by default. Are the 1.9 instructions also good?
My goal is to setup a real cloud internally for testing our system running cloud services, bare metal and virtual. I want to install OpenStack Autopilot, for which Ubuntu has instructions here https://help.ubuntu.com/lts/clouddocs/en/Installing-MAAS.html for installing MAAS, but I'm not sure which version (looks like 1.9 or older).
MAAS 1.9 and 2.0 have different tabs and organization.
Ubuntu 14.04 installs MAAS 1.9 by default.
Ubuntu 16.04 installs MAAS 2.0 by default.
I really don't care which version. Just one that works when I follow the instructions. Maybe there are variables in the hardware I'm using or how I have set it up. That's the reason I wanted to see the "description of a typical setup".

-Dick

**Comment by pmatulis** [comment]
@GitVail I strongly recommend Ubuntu 16.04 with MAAS 2.0. The instructions on help.ubuntu.com are for MAAS 1.9 so that won't work so well. As for setting up OpenStack, the method used is influenced by how many MAAS nodes (and the resources of each: CPU and RAM). If you have a single, but very strong, machine then you can install MAAS via LXD containers, all locally.

The "description of a typical setup" is quite short and essentially just says that all MAAS components (i.e. region controller and rack controller) can be placed on the same machine:

> **A simple MAAS setup**
The key components of a MAAS installation are:
- Region controller(s)
- Rack controller(s)
- MAAS machines (nodes)

> For a small setup, it is typical to have a single region controller and a single rack controller. In addition, both can reside on the same system. This is easy to achieve by simply installing the maas metapackage. It is only worth having multiple region and rack controllers if you need to organise your nodes into different subnets and you want high availability and/or load balancing. Consideration of DHCP is recommended if your network is already providing this service.

**Comment by GitVail** [comment]
Thanks for your help, Peter!
I've tried both and run into roadblocks:
                U14+M1.9:          All Nodes failed commissioning
                U16:M2.0:           None of the MAAS instructions match the actual web interface
I was following the recommendation of 5 machines with 2 disks each, 2 machines with 2 NICs, a dedicated switch for LAN, and internet access thru router on LAN. I have several machines, all AMD Kaveri's w/8GB and big disks.
Instructions have been unclear on the use for each machine.
#1 with 2 NICs is the controller
#2 with 2 NICs is ???
#'s 3,4,5 are Nodes?

And I'm not sure about the connections of the router on the LAN. If the machines are connected to the switch, then how does the router do its job?

-Dick

**Comment by GitVail** [comment]
Hi Peter,
Hope you had a good Monday off too.

I guess I'm confused by the multiple versions of MAAS documentation. I'm a Ubuntu fan and want to implement OpenStack in our lab. Ignoring the OpenStack docs on the OpenStack.org site, Ubuntu has Official Documentation for deploying production grade OpenStack with MAAS, Juju and Landscape docs here (https://help.ubuntu.com/lts/clouddocs/en/Intro.html?_ga=1.90717786.1572867642.1441036546) that include installing MAAS installation instructions different from the MAAS instructions here http://maas.io/docs/ which are version specific.

If my goal is OpenStack on Ubuntu (and there are several other distro choices with their own instructions), should I start with the Ubuntu OpenStack MAAS instructions or MAAS's MAAS instructions?

Can you tell me which version of Ubuntu and MAAS are the Official Ubuntu OpenStack MAAS instructions about?

And do any of the above methods have a suggested minimum hardware and network configuration? I see that MAAS can do DHCP for the private net, but so can a router which can also do NAT.

-Dick

**Comment by pmatulis** [comment]
@GitVail 
Regarding the two sites differing on how MAAS is installed, yes, the help.ubuntu.com guide only offers to install the 'maas' package whereas the maas.io site includes that method in addition to a distributed method (all components not on a single machine). Also, and more importantly, the help.ubuntu.com guide is based on 14.04 and an old version of MAAS (1.7). Unfortunately, this is not spelled out. Use that guide only to obtain a general knowledge of MAAS. Thanks for bringing it up.

You do need significant computing power to run OpenStack. If using MAAS you will obviously require a machine for it as well. The Ubuntu way for installing OpenStack is with Juju and MAAS along with some kind of automated OpenStack installer. Yet each installer has its particular requirements for the machines it will use because they each build a cloud in a different way. So I don't have a simple answer to your question. I may want to first become familiar with Juju and MAAS before considering OpenStack.

You may also want to follow the [conjure-up](http://conjure-up.io) project. It is one of the installers I alluded to above but it depends on "spells" (cloud-building instructions). If you have a single massive system you can install a cloud on it via LXD containers with a single command.

Any further questions you may have would be best handled via traditional support channels such as the public IRC channels on Freenode: 'ubuntu-server', 'maas', 'juju'. There are also these mailing lists: [Ubuntu Server](http://lists.ubuntu.com/mailman/listinfo/ubuntu-server) and [Juju](https://lists.ubuntu.com/mailman/listinfo/juju).

**Comment by GitVail** [comment]
OK and thanks for your help. Are you still going to fix the link?
http://maas.io/docs/intro-about-maas#a-simple-maas-setup

-Dick

**Comment by pmatulis** [comment]
Yes, this has been fixed. We just need to wait for the changes to be published.
